version: "3"
services:
  mongo:
    image: mongo:4
    command: --wiredTigerCacheSizeGB 2
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  elastic:
    image: elasticsearch:5.6
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  ada:
    # replace this with the published version from docker hub once it exists
    build: .
    environment:
      - ADA_MONGO_DB_URI=mongodb://mongo:27017/ada?rm.nbChannelsPerNode=20
      - ADA_ELASTIC_DB_HOST=elastic:9200
    volumes:
      - ./ada.conf:/home/ada/ada-web/conf/custom.conf
      - ada-datasetimport:/home/ada/datasetimport
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - elastic
volumes:
  elastic-data:
    driver: local
  mongo-data:
    driver: local
  ada-datasetimport:
    driver: local